version: "3.9"
volumes:
  postgres_kc_data:
    driver: local
services:
  postgres:
    image: postgres:14.2
    volumes:
      - postgres_kc_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chefs
