name: Deploy

env:
  ACRONYM: chefs

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: Pull request number, leave blank for dev/test/prod deployment
        required: false
        type: string
      environment:
        description: Environment name; choose dev for PR
        required: true
        type: choice
        options:
        - dev
        - test
        - prod
        default: dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.pr-number || github.ref }}
  cancel-in-progress: true

jobs:
  set-vars:
    name: Set variables
    id: precheck
    runs-on: ubuntu-latest
    outputs:
      APP_TITLE: ${{ steps.vars.outputs.APP_TITLE }}
      ENVIRONMENT: ${{ steps.vars.outputs.ENVIRONMENT }}
      JOB_NAME: ${{ steps.vars.outputs.JOB_NAME }}
      ROUTE_PATH: ${{ steps.vars.outputs.ROUTE_PATH }}
      URL: ${{ steps.vars.outputs.URL }}
    steps:
      - name: Setting variables
        id: default-vars
        env:
          PR_NUMBER: ${{ github.event.inputs.pr-number }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          ACRONYM: ${{ env.ACRONYM }}
        run: |
          echo "APP_TITLE=Common Hosted Forms" >> "$GITHUB_OUTPUT"
          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_OUTPUT"
          echo "JOB_NAME=master" >> "$GITHUB_OUTPUT"
          echo "ROUTE_PATH=/app" >> "$GITHUB_OUTPUT"
          echo "URL=https://$ACRONYM-$ENVIRONMENT.apps.silver.devops.gov.bc.ca" >> "$GITHUB_OUTPUT"
      - name: Final variables
        id: vars
        env:
          PR_NUMBER: ${{ github.event.inputs.pr-number }}
        run: |
          if [[ "$PR_NUMBER" != '' ]]; then
            echo "APP_TITLE=${{ steps.default-vars.outputs.APP_TITLE }} - PR-$PR_NUMBER" >> "$GITHUB_OUTPUT"
            echo "ENVIRONMENT=pr" >> "$GITHUB_OUTPUT"
            echo "JOB_NAME=pr-$PR_NUMBER" >> "$GITHUB_OUTPUT"
            echo "ROUTE_PATH=/pr-$PR_NUMBER" >> "$GITHUB_OUTPUT"
            echo "URL=${{ steps.default-vars.outputs.URL }}/pr-$PR_NUMBER" >> "$GITHUB_OUTPUT"
          else
            echo "APP_TITLE=${{ steps.default-vars.outputs.APP_TITLE }}" >> "$GITHUB_OUTPUT"
            echo "ENVIRONMENT=${{ steps.default-vars.outputs.ENVIRONMENT }}" >> "$GITHUB_OUTPUT"
            echo "JOB_NAME=${{ steps.default-vars.outputs.JOB_NAME }}" >> "$GITHUB_OUTPUT"
            echo "ROUTE_PATH=${{ steps.default-vars.outputs.ROUTE_PATH }}" >> "$GITHUB_OUTPUT"
            echo "URL=${{ steps.default-vars.outputs.URL }}/app" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build & Push
    runs-on: ubuntu-latest
    needs: set-vars
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & Push
        uses: ./.github/actions/build-push-container
        with:
          context: .
          image_name: ${{ vars.APP_NAME }}
          github_username: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_title: ${{ needs.set-vars.outputs.APP_TITLE }}
          route_path: ${{ needs.set-vars.outputs.ROUTE_PATH }}
          app_contact: ${{ vars.CHEFS_CONTACT }}

  deploy:
    name: Deploys to selected environment
    runs-on: ubuntu-latest
    needs: [set-vars, build]
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to environment
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ vars.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          environment: ${{ needs.set-vars.outputs.ENVIRONMENT }}
          job_name: ${{ needs.set-vars.outputs.JOB_NAME }}
          namespace_prefix: ${{ vars.NAMESPACE_PREFIX }}
          namespace_environment: ${{ github.event.inputs.environment }}
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          server_host: ${{ vars.SERVER_HOST }}
          route_path: ${{ needs.set-vars.outputs.ROUTE_PATH }}
          route_prefix: ${{ vars.ROUTE_PREFIX }}
      - name: Release Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event.inputs.pr-number != '' && success()
        with:
          header: release
          message: |
            Release ${{ github.sha }} deployed at <https://${{ env.ACRONYM }}-dev.apps.silver.devops.gov.bc.ca/pr-${{ github.event.inputs.pr-number }}>